# Generated by Django 3.2.3 on 2023-08-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
